### PR TITLE
New subgraphs

### PR DESCRIPTION
**Pull request by eddiemonroe**

### CODE REVIEW

**Comment by linas** [comment]
Hey Eddie, typically, you want to keep code and data separate, so that giant data files don't glom up the git repo, making it unmanagable for code...

**Comment by eddiemonroe** [comment]
Hey Linas, yeah, I considered a separate repo just for the data as a possibility. We have a lot of data in the bio project that is being generated and updated regularly. We could put the data files on a server with ftp access, but git does provide a nice way to update easily and to have revision history. What would you recommend? Separate repo just for the data?

**Comment by linas** [comment]
Yes, a separate repo just for data.  The problem is that, over time, the repos get large, because they carry all the history, and so cloning them becomes time-consuming, and they also start eating up disk-space (all the old copies are there, in everyone's copy of the repo).  Its not a big deal, but its good practice.

**Comment by eddiemonroe** [comment]
Ah, makes sense, thanks.

**Pull request merged**
