### PR TITLE
Adds a Pharmgkb pathway type

### PR DESCRIPTION
**Pull request by tanksha**
Adds a PharmGkb pathway node type to identify Pathways from https://www.pharmgkb.org/ database.

### CODE REVIEW

**Comment by linas** [comment]
You should add the above commit message to the file itself.  That is, the actual change should be:
```
// The PharmGkb type identifies pathways from https://www.pharmgkb.org/ database.
PHARM_GKB_NODE <- PATHWAY_NODE
```

Also, all the other types should be documented as well.  Writing code without writing documentation to go with it is terrible programming practice.  And do not be fooled -- the `atom_types.script` is ***code*** just like any other code in the system.  It is not wome weird exception to the rule.

**Comment by linas** [comment]
This also needs to be done for pull req #102, which was never done.

**Comment by tanksha** [comment]
@mjsduncan Please review the documentations added. I also add the modifications we discussed to introduce Ontology and drugbank types.

**Comment by linas** [comment]
Thank you!

**Comment by mjsduncan** [comment]
thanks, hedra!

**Pull request merged**
